# Copyright (c) 2026, Tranquil Data, Inc. All rights reserved.

openapi: 3.0.0

info:
  title: Tranquil Data (TM) Hub Edition APIs
  description: >
    This is the complete API for the agent hub. It covers routines for looking
    up subject, schema, and variable state as well as reding from and writing to
    the durable cache.
  version: 1.0.1
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

externalDocs:
  description: "Find out more about Tranquil Data"
  url: "https://tranquildata.com"

tags:
  - name: root
    description: Routines to query status and state for a specific peer.

servers:
  - url: http://localhost

paths:

  #
  # Root API paths
  #

  /:

    head:
      tags:
        - root
      summary: Test that this peer is running and ready
      operationId: checkPeer
      responses:
        '200':
          description: The peer is available and responsive
        '500':
          description: There is some internal error with the peer

